run:
  timeout: 5m
linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocyclo
    - gofmt
    - misspell
    - nakedret
    - unconvert
    - unparam
    - whitespace
    - goimports
    - exportloopref
