definitions:
  models.Flight:
    properties:
      aircraft:
        type: string
      airline:
        type: string
      destination:
        type: string
      flight:
        type: string
      hour_arr:
        type: string
      hour_dep:
        type: string
      origin:
        type: string
      status:
        type: string
      terminal_arr:
        type: string
      terminal_dep:
        type: string
    type: object
host: localhost:8000
info:
  contact: {}
  description: This is a sample server for managing flight information.
  title: Flights API
  version: "1.0"
paths:
  /api/flights:
    get:
      description: Get the list of latest flights
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Flight'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get last flights
      tags:
      - flights
  /api/flights/{id}:
    get:
      description: Get details of a flight by its id flight
      parameters:
      - description: Flight ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Flight'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get flight by id flight
      tags:
      - flights
swagger: "2.0"
