name: CI

on:
  push:
    branches:
      - main
      - master
      - '**/*.go'
  pull_request:
    branches:
      - main
      - master

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.20'

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.58

  tests:
    runs-on: ubuntu-latest
    needs: lint

    services:
      redis:
        image: redis:alpine
        ports:
          - 6379:6379

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.20'

      - name: Install dependencies
        run: go mod download

      - name: Run unit tests
        run: go test -v ./...